-- Ejecutar una sola vez en Supabase > SQL Editor.
-- Nora usa la service_role key solo en el servidor, nunca en el navegador.
create table if not exists public.nora_users (
  id text primary key,
  email text unique not null,
  payload jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.nora_events (
  id bigint generated by default as identity primary key,
  user_id text,
  event_name text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.nora_sessions (
  id text primary key,
  payload jsonb not null,
  expires_at timestamptz not null,
  updated_at timestamptz not null default now()
);

alter table public.nora_users enable row level security;
alter table public.nora_events enable row level security;
alter table public.nora_sessions enable row level security;
-- Sin políticas para anon: el acceso se hace únicamente desde el servidor con service_role.
